In [66]:
import pandas as pd
import numpy as np

In [89]:
df=pd.read_csv('dataset_1.csv')
print(df.columns)
df=df.drop(['色相','Unnamed: 0'],axis=1)

df["衣服ID"]=[i[:-3] for i in df["衣服ID"]]
df

Index(['Unnamed: 0', '客户ID', '衣服单价', '衣服ID', '款式流水号', '颜色深度', '年份', '季节',
       '小类号码', '颜色式样', '颜色大类', '颜色名称', '品名', '大类', '中类', '品牌定义廓形', '领型', '袖长',
       '系列', '尺寸组', '标准价', '色相', '色温', '色明度', '色纯度', '对比度', '色调', '廓形', '宽松度',
       '长度', '款设图-大小复杂度', '款设图-规则性', '款设图-曲直', '材质-垂感', '整体曲直', '量感', '场合',
       '领型-形状', '领型-曲直', '领型-量感', '裙型裤型'],
      dtype='object')


客户ID  衣服单价          衣服ID  款式流水号  颜色深度     年份  季节  小类号码 颜色式样 颜色大类  \
0       483     2  JWWC11101000      1     0  2016年  春季   111   素色  黑色系   
1       483     1  JWWC31301215      1     5  2016年  春季   313   条纹  白色系   
2       483     2  JWXC60102100      2     0  2017年  春季   601   花纹  黑色系   
3       506     4  JWWC31001100      1     0  2016年  春季   310   花纹  黑色系   
4       513     2  JWWX11204000      4     0  2016年  夏季   112   素色  黑色系   
5       513     3  JWXX20103126      3     6  2017年  夏季   201   花纹  蓝色系   
6       513     4  JWXX60201100      1     0  2017年  夏季   602   花纹  黑色系   
7       781     2  JWXC20207100      7     0  2017年  春季   202   花纹  黑色系   
8       781     5  JWXX50014026     14     6  2017年  夏季   500   素色  蓝色系   
9       781     2  JWXX11502220      2     0  2017年  夏季   115   条纹  蓝色系   
10      781     3  JWXX42003220      3     0  2017年  夏季   420   条纹  蓝色系   
11      781     4  JWXX80314000     14     0  2017年  夏季   803   素色  黑色系   
12      971     5  JWXC30604000      4     0  2017年  春季   306   素色  黑色系   
13      971     6  JWXC41201000      1     0  2017年  春季   412   素色  黑色系   
14      971     2  JWXC40501100      1     0  2017年  春季   405   花纹  黑色系   
15      971     2  JWXC40501100      1     0  2017年  春季   405   花纹  黑色系   
16      971     5  JWXC50037100     37     0  2017年  春季   500   花纹  黑色系   
17      971     5  JWXC50004084      4     4  2017年  春季   500   素色  绿色系   
18      971     2  JWXX30702015      2     5  2017年  夏季   307   素色  白色系   
19      984     8  JWWD03205126      5     6  2016年  冬季    32   花纹  蓝色系   
20      984     4  JWXC31005100      5     0  2017年  春季   310   花纹  黑色系   
21      984     3  JWXC31103100      3     0  2017年  春季   311   花纹  黑色系   
22      984     1  JWXX81101115      1     5  2017年  夏季   811   花纹  白色系   
23      984     2  JWXX80333127     33     7  2017年  夏季   803   花纹  蓝色系   
24      984     3  JWXX11203000      3     0  2017年  夏季   112   素色  黑色系   
25      984     5  JWXX50034115     34     5  2017年  夏季   500   花纹  白色系   
26      984     5  JWXX50034115     34     5  2017年  夏季   500   花纹  白色系   
27      984     1  JWXX80316100     16     0  2017年  夏季   803   花纹  黑色系   
28      984     3  JWXX11207065      7     5  2017年  夏季   112   素色  黄色系   
29     1611     6  JWXC31504157      4     7  2017年  春季   315   花纹  红色系   
..      ...   ...           ...    ...   ...    ...  ..   ...  ...  ...   
969  225596     3  JWXX80315126     15     6  2017年  夏季   803   花纹  蓝色系   
970  226657     3  JWXC50029300     29     0  2017年  春季   500   格子  黑色系   
971  226657     2  JWXC11107057      7     7  2017年  春季   111   素色  红色系   
972  226657     2  JWXQ80301115      1     5  2017年  秋季   803   花纹  白色系   
973  226657     2  JWXX11206000      6     0  2017年  夏季   112   素色  黑色系   
974  226657     2  JWXX31206065      6     5  2017年  夏季   312   素色  黄色系   
975  227549     8  JWXC30601000      1     0  2017年  春季   306   素色  黑色系   
976  227549     2  JWXC31301000      1     0  2017年  春季   313   素色  黑色系   
977  227549     2  JWXC80204100      4     0  2017年  春季   802   花纹  黑色系   
978  227549     2  JWXX11101055      1     5  2017年  夏季   111   素色  红色系   
979  227549     3  JWXX40510100     10     0  2017年  夏季   405   花纹  黑色系   
980  227549     5  JWXX40508080      8     0  2017年  夏季   405   素色  绿色系   
981  227549     5  JWXX30701126      1     6  2017年  夏季   307   花纹  蓝色系   
982  227549     4  JWXX80342300     42     0  2017年  夏季   803   格子  黑色系   
983  227549     8  JWXQ51006157      6     7  2017年  秋季   510   花纹  红色系   
984  227675     2  JWXC11102100      2     0  2017年  春季   111   花纹  黑色系   
985  227675     2  JWXC11108127      8     7  2017年  春季   111   花纹  蓝色系   
986  227675     3  JWXC42001026      1     6  2017年  春季   420   素色  蓝色系   
987  227675     2  JWXC31001215      1     5  2017年  春季   310   条纹  白色系   
988  227675     2  JWXX31207215      7     5  2017年  夏季   312   条纹  白色系   
989  227675     1  JWXX11301100      1     0  2017年  夏季   113   花纹  黑色系   
990  227675     2  JWXX80312100 

In [90]:
#产生userID集与itemID集
items=df.drop(['客户ID'],axis=1).drop_duplicates(['衣服ID'])#物品特征表
itemsID=items['衣服ID']#物品id表
userID=df['客户ID'].drop_duplicates()#去重
b=items.pop('衣服ID')
items.insert(0,'衣服ID',b)

In [91]:
#需要onehot编码的列名
cols=[  '衣服单价',  '款式流水号', '颜色深度', '年份', '季节',
       '小类号码', '颜色式样', '颜色大类', '颜色名称', '品名', '大类', '中类', '品牌定义廓形', '领型', '袖长',
       '系列', '尺寸组', '标准价', '色温', '色明度', '色纯度', '对比度', '色调', '廓形', '宽松度',
       '长度', '款设图-大小复杂度', '款设图-规则性', '款设图-曲直', '材质-垂感', '整体曲直', '量感', '场合',
       '领型-形状', '领型-曲直', '领型-量感', '裙型裤型']
items.columns

Index(['衣服ID', '衣服单价', '款式流水号', '颜色深度', '年份', '季节', '小类号码', '颜色式样', '颜色大类',
       '颜色名称', '品名', '大类', '中类', '品牌定义廓形', '领型', '袖长', '系列', '尺寸组', '标准价',
       '色温', '色明度', '色纯度', '对比度', '色调', '廓形', '宽松度', '长度', '款设图-大小复杂度',
       '款设图-规则性', '款设图-曲直', '材质-垂感', '整体曲直', '量感', '场合', '领型-形状', '领型-曲直',
       '领型-量感', '裙型裤型'],
      dtype='object')

In [46]:
import matplotlib.pyplot as plt


def dv_encoder(data):#oneHot编码
    # Importing the dataset
    X=data.iloc[:,:].values#转化为numpy
    
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
    for i in range(1,15):
        labelencoder_X = LabelEncoder(encoding='utf-8')
        X[:, i] = labelencoder_X.fit_transform(X[:,i])
        
    onehotencoder = OneHotEncoder(categorical_features = list(range(1,10)))
    y = onehotencoder.fit_transform(X).toarray()
    
    return y

TypeError: object() takes no parameters

In [ ]:
dataset = pd.read_csv('Data.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [43]:
list(range(14,15))

[14]

In [96]:
Bitems=pd.get_dummies(items,columns=cols)
print(Bitems)
Bitems=Bitems.drop(['衣服ID'],axis=1)

             衣服ID  衣服单价_1  衣服单价_2  衣服单价_3  衣服单价_4  衣服单价_5  衣服单价_6  衣服单价_7  \
0    JWWC11101000       0       1       0       0       0       0       0   
1    JWWC31301215       1       0       0       0       0       0       0   
2    JWXC60102100       0       1       0       0       0       0       0   
3    JWWC31001100       0       0       0       1       0       0       0   
4    JWWX11204000       0       1       0       0       0       0       0   
5    JWXX20103126       0       0       1       0       0       0       0   
6    JWXX60201100       0       0       0       1       0       0       0   
7    JWXC20207100       0       1       0       0       0       0       0   
8    JWXX50014026       0       0       0       0       1       0       0   
9    JWXX11502220       0       1       0       0       0       0       0   
10   JWXX42003220       0       0       1       0       0       0       0   
11   JWXX80314000       0       0       0       1       0       0       0   

In [93]:
from sklearn.neighbors import NearestNeighbors
""" 
NearestNeighbors用到的参数解释 
n_neighbors=5,默认值为5，表示查询k个最近邻的数目 
algorithm='auto',指定用于计算最近邻的算法，auto表示试图采用最适合的算法计算最近邻 
fit(X)表示用X来训练算法 
"""  
nbrs = NearestNeighbors(n_neighbors=322, algorithm="ball_tree").fit(Bitems)  
#返回距离每个点k个最近的点和距离指数，indices可以理解为表示点的下标，distances为距离  
distances, indices = nbrs.kneighbors(Bitems)  
print (indices ) 
print(distances)  

[[  0 197 101 ... 310 225  91]
 [  1  55 181 ... 159 190 261]
 [  2 106 190 ... 215  83  56]
 ...
 [319 116 207 ... 122 216 263]
 [320  94 313 ... 162  44 133]
 [321   1 181 ...  44 234  37]]
[[0.         3.74165739 4.35889894 ... 8.         8.         8.1240384 ]
 [0.         4.58257569 5.47722558 ... 7.93725393 7.93725393 8.        ]
 [0.         4.89897949 5.29150262 ... 7.68114575 7.74596669 7.74596669]
 ...
 [0.         5.09901951 5.19615242 ... 8.1240384  8.1240384  8.18535277]
 [0.         4.89897949 5.29150262 ... 7.81024968 7.81024968 7.81024968]
 [0.         5.56776436 5.56776436 ... 7.87400787 7.87400787 8.        ]]


In [98]:
#编写userID_itemID矩阵
user_item=pd.DataFrame(index=userID,columns=itemsID)

In [97]:
    a=df.groupby('客户ID')
    for user,grouped in a:
        for item in grouped['衣服ID']:
            user_item[user,item]=1    

ValueError: Names should be list-like for a MultiIndex